// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfIAasFkz2Z7d6WNOp79eeCpYnx-_8MAs',
    appId: '1:376407238677:web:01bfeaad46dc453e10c61c',
    messagingSenderId: '376407238677',
    projectId: 'skripsi-2022-zefanyawijaya',
    authDomain: 'skripsi-2022-zefanyawijaya.firebaseapp.com',
    storageBucket: 'skripsi-2022-zefanyawijaya.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj2sDiP2BNTZEDA1t64W1uxNDb3i-jBfk',
    appId: '1:376407238677:android:f5084f12f315c02510c61c',
    messagingSenderId: '376407238677',
    projectId: 'skripsi-2022-zefanyawijaya',
    storageBucket: 'skripsi-2022-zefanyawijaya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG4AJPXRolcjk5MfcTlpK2zARcm-y-o5E',
    appId: '1:376407238677:ios:5a8e6ba672226f0e10c61c',
    messagingSenderId: '376407238677',
    projectId: 'skripsi-2022-zefanyawijaya',
    storageBucket: 'skripsi-2022-zefanyawijaya.appspot.com',
    iosClientId: '376407238677-po97cgm81q10hl6fvkvnvr2fagmapogd.apps.googleusercontent.com',
    iosBundleId: 'com.example.spkSawWheyProtein',
  );
}
