; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "SPK SAW Whey Protein"
#define MyAppVersion "1.0"
#define MyAppPublisher "Zefanya Wijaya"
#define MyAppURL "https://skripsi-2022-zefanyawijaya.web.app/#/"
#define MyAppExeName "spk_saw_whey_protein.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{36777279-3F03-4540-BE65-04000F52FC92}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=D:\PROJEK SKRIPSI LANJUTAN\Program\flutter_fe\spk_saw_whey_protein\Installers
OutputBaseFilename=SPK_SAW_Zefanya_Wijaya
SetupIconFile=D:\PROJEK SKRIPSI LANJUTAN\flutter.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\PROJEK SKRIPSI LANJUTAN\Program\flutter_fe\spk_saw_whey_protein\build\windows\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\PROJEK SKRIPSI LANJUTAN\Program\flutter_fe\spk_saw_whey_protein\build\windows\runner\Release\file_saver_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\PROJEK SKRIPSI LANJUTAN\Program\flutter_fe\spk_saw_whey_protein\build\windows\runner\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\PROJEK SKRIPSI LANJUTAN\Program\flutter_fe\spk_saw_whey_protein\build\windows\runner\Release\sentry_flutter_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\PROJEK SKRIPSI LANJUTAN\Program\flutter_fe\spk_saw_whey_protein\build\windows\runner\Release\url_launcher_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\PROJEK SKRIPSI LANJUTAN\Program\flutter_fe\spk_saw_whey_protein\build\windows\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

