class GetListRankingWheyProteinFailed implements Exception {}

class GetListRankingWheyProteinErrorInternalServer implements GetListRankingWheyProteinFailed{}

class GetListRankingWheyUnknownErrorCode implements GetListRankingWheyProteinFailed{}