class GetCalculateWheyBySearchFailed implements Exception {}

class GetCalculateWheyBySearchErrorInternalServer implements GetCalculateWheyBySearchFailed {}

class GetCalculateWheyUnknownErrorCode implements GetCalculateWheyBySearchFailed{}